on: [pull_request]
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  list-modules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.modules.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: modules
        run: echo "::set-output name=matrix::$(find aws -type d -maxdepth 2 | jq -R -s -c 'split("\n")[:-1]')"

  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    needs: list-modules
    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        modules: ${{ fromJson(needs.list-modules.outputs.matrix) }}

    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${{ matrix.modules }} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Generate Infracost diff
        run: |
          infracost diff --path=${{ matrix.modules }} \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json

      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{github.token}} \
                                     --pull-request=${{github.event.pull_request.number}} \
                                     --behavior=new