name: Lint
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  list-modules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.modules.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: modules
        run: echo "::set-output name=matrix::$(find aws -type d -maxdepth 2 -not -path 'aws' -not -path '*/modules' | jq -R -s -c 'split("\n")[:-1]')"

  tflint:
    runs-on: ubuntu-latest
    needs: list-modules

    strategy:
      matrix:
        modules: ${{ fromJson(needs.list-modules.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v3
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run:  tflint -f compact ${{ matrix.modules }}